### ISSUE TITLE
KeyError: 'Location'

### ISSUE THREAD

**Issue by TimoD87** [CJNE/pyporscheconnectapi#31]
Now it worked for some hours, but now I get an new error:

```
Traceback (most recent call last):
  File "/home/pi/pypo-main/cli.py", line 4, in <module>
    cli()
  File "/home/pi/pypo-main/pyporscheconnectapi/cli.py", line 270, in cli
    loop.run_until_complete(main(args))
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/pi/pypo-main/pyporscheconnectapi/cli.py", line 67, in main
    data = await client.getCurrentOverview(vin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/pypo-main/pyporscheconnectapi/client.py", line 460, in getCurrentOverview
    progressResult = await self._connection.post(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/pypo-main/pyporscheconnectapi/connection.py", line 251, in post
    headers = await self._createhead(application)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/pypo-main/pyporscheconnectapi/connection.py", line 296, in _createhead
    token = await self._requestToken(
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/pypo-main/pyporscheconnectapi/connection.py", line 211, in _requestToken
    await self._login()
  File "/home/pi/pypo-main/pyporscheconnectapi/connection.py", line 177, in _login
    resume_url = resp.headers['Location']
                 ~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'Location'
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fb867b390>
ERROR:asyncio:Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fb8277c40>, 38.411622587)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fb82b2f90>
```

Maybe they changed something in the response from the server?

**Comment by sracing** [comment]
Same here. I can confirm the same error after some hours.
