### ISSUE TITLE
Cannot load data

### ISSUE THREAD

**Issue by woozar** [CJNE/pyporscheconnectapi#42]
I have got a new error (at least for me it is new)

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/porscheconnect/__init__.py", line 215, in _async_update_data
    vehicle["services"] = await self.controller.getServices(vin)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyporscheconnectapi/client.py", line 488, in getServices
    is_privacy = data['vehicleServiceEnabledMap']['VSR'] == 'DISABLED'
                 ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'vehicleServiceEnabledMap'

**Comment by woozar** [comment]
Oops wrong repo
