### ISSUE TITLE
Cannot activate integration because of required Captcha

### ISSUE THREAD

**Issue by snah-private** [CJNE/pyporscheconnectapi#44]
It's impossible to activate the integration because the login flow uses a Captcha challenge.
See next log messages:

2024-03-17 16:27:15.224 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry *****@******.com for porscheconnect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 504, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/porscheconnect/__init__.py", line 94, in async_setup_entry
    access_tokens = await controller.getAllTokens()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyporscheconnectapi/client.py", line 32, in getAllTokens
    return await self._connection.getAllTokens()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyporscheconnectapi/connection.py", line 259, in getAllTokens
    token = await self._requestToken(application)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyporscheconnectapi/connection.py", line 266, in _requestToken
    await self._login()
  File "/usr/local/lib/python3.12/site-packages/pyporscheconnectapi/connection.py", line 175, in _login
    raise captchaRequired("Captcha required")
pyporscheconnectapi.exceptions.CaptchaRequired

**Comment by fredriklj** [comment]
I am closing this issue as the APIs we relied on have been retired. C.f #46
