### ISSUE TITLE
Client error '429 Too Many Requests' 

### ISSUE THREAD

**Issue by fredriklj** [CJNE/pyporscheconnectapi#63]
2024-12-06 14:01:06.106 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [138122696809280] Unexpected exception
    Traceback (most recent call last):
      File "/usr/local/lib/python3.12/site-packages/pyporscheconnectapi/connection.py", line 87, in request
        resp.raise_for_status()
        ^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.12/site-packages/httpx/_models.py", line 763, in raise_for_status
        raise HTTPStatusError(message, request=request, response=self)
    httpx.HTTPStatusError: Client error '429 Too Many Requests' for url 'https://api.ppa.porsche.com/app//connect/v1/vehicles/.../commands'

I've also noticed that some times you get 429 (Too many requests) in response when calling a remote service. This error seem to mostly be temporary, as another call shortly thereafter seem to have a high probability of succeeding. We should wait for a few seconds and then do one or two retries.

**Comment by paulhargreaves** [comment]
The 429 causes Porsche connect to fail btw. All sensors turn to Unavailable until HA is restarted.

```
...
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/pyporscheconnectapi/vehicle.py", line 210, in get_stored_overview
    self.status = await self.connection.get(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
        f"/connect/v1/vehicles/{self.vin}?{measurements}",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/pyporscheconnectapi/connection.py", line 70, in get
    return await self.request("GET", url, params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyporscheconnectapi/connection.py", line 99, in request
    raise PorscheExceptionError(exc.response.status_code) from exc
pyporscheconnectapi.exceptions.PorscheExceptionError
2025-06-05 01:17:41.078 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up porscheconnect platform for sensor: 'name'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/porscheconnect/sensor.py", line 167, in async_setup_entry
    PorscheSensor(coordinator, vehicle, description)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
```

**Comment by fredriklj** [comment]
This is the behaviour of the API unfortunately. You should be able to make it running by reloading the integration, but I'll look into having some automatic retry after some time to get it up again.

**Comment by fredriklj** [comment]
addressed in #93
