### ISSUE TITLE
'type' object is not subscriptable

### ISSUE THREAD

**Issue by MarkusGH** [CJNE/pyporscheconnectapi#64]
After updating to the new release (from the working new_api branch) I get this error: 

`Traceback (most recent call last):
  File "/usr/local/bin/porschecli", line 5, in <module>
    from pyporscheconnectapi.cli import cli
  File "/usr/local/lib/python3.8/dist-packages/pyporscheconnectapi/cli.py", line 6, in <module>
    from pyporscheconnectapi.account import PorscheConnectAccount
  File "/usr/local/lib/python3.8/dist-packages/pyporscheconnectapi/account.py", line 2, in <module>
    from pyporscheconnectapi.vehicle import PorscheVehicle
  File "/usr/local/lib/python3.8/dist-packages/pyporscheconnectapi/vehicle.py", line 20, in <module>
    class PorscheVehicle:
  File "/usr/local/lib/python3.8/dist-packages/pyporscheconnectapi/vehicle.py", line 207, in PorscheVehicle
    def location(self) -> tuple[Optional[int], Optional[int], Optional[int]]:
TypeError: 'type' object is not subscriptable
`

What can I do to resolve this? 

`pip uninstall pyporscheconnectapi`  + `pip install pyporscheconnectapi` did not help.

**Comment by MarkusGH** [comment]
Got it - pyporscheconnect needs python 3.9 now. I suggest fixing the documentation or fixing the code.

**Comment by fredriklj** [comment]
Thanks for the heads-up. And yes, everything older than 3.9 is end-of-life by now. I updated the requirements to 3.9, but now sure everything will work ok with that old version either. I suggest you move to 3.12 or 3.13.

**Comment by fredriklj** [comment]
Fixed in #68ef782
